# Generated by Django 2.2.6 on 2019-11-20 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commissionsofprofcom',
            options={'ordering': ['title'], 'verbose_name': 'Комиссии профкома', 'verbose_name_plural': 'Комиссии профкома'},
        ),
        migrations.AlterModelOptions(
            name='helpforproforg',
            options={'ordering': ['title'], 'verbose_name': 'В помощь профоргу', 'verbose_name_plural': 'В помощь профоргу'},
        ),
        migrations.AlterModelOptions(
            name='helpforstudentproforg',
            options={'ordering': ['title'], 'verbose_name': 'В помощь студенческому профоргу', 'verbose_name_plural': 'В помощь студенческому профоргу'},
        ),
        migrations.AlterModelOptions(
            name='legislativeregulatoryandstatutorydocuments',
            options={'ordering': ['title'], 'verbose_name': 'Законодательные, нормативные и уставные документы', 'verbose_name_plural': 'Законодательные, нормативные и уставные документы'},
        ),
        migrations.AlterModelOptions(
            name='protectionofpersonalinformation',
            options={'ordering': ['title'], 'verbose_name': 'Защита персональных данных', 'verbose_name_plural': 'Защита персональных данных'},
        ),
        migrations.AlterModelOptions(
            name='themainactivitiesofproforg',
            options={'ordering': ['title'], 'verbose_name': 'Основные направления деятельности профорга', 'verbose_name_plural': 'Основные направления деятельности профорга'},
        ),
        migrations.AlterModelOptions(
            name='usefullinks',
            options={'ordering': ['title'], 'verbose_name': 'Полезные ссылки', 'verbose_name_plural': 'Полезные ссылки'},
        ),
    ]
